metrics: don't check for EACL get in S3 test
This test fails after upgrade to S3 0.43.0:

    AssertionError: invalid value for neofs_s3_pool_container_eacl_duration_bucket
    assert 0 &gt;= 1
     +  where 0 = len([])

Because of two things:
 * EACL PUT updates EACL cache and subseqeunt EACL GET may not trigger any
   requests to NeoFS
 * versions before 0.43.0 polled NeoFS for EACL PUT result (as required by
   pre-2.21 API) triggering updates to this metric, now they rely on 2.21+ API
   that has synchronous PUT

There are three ways to deal with it:
 * wait for cache expiration, but it's 2m by default, too long
 * tune cache timeout and do the same as above, doesn't seem to be justified
 * just don't check this specific metric, that's what we do here

Signed-off-by: Roman Khimov <roman@nspcc.ru>